### ISSUE TITLE
项目怎么运行

### ISSUE THREAD

**Issue by gongfuxiaocai** [mjzhang1993/react-router4-template#1]
你好，你的项目怎么运行的，四个指令都跑了一遍也没把项目跑起来，麻烦你指点下，谢谢啦

**Comment by mjzhang1993** [comment]
抱歉！ 无法运行的原因应该是一个** 插件的版本问题**`"chunk-manifest-webpack-plugin": ^1.1.0"` 通过 `npm install` 安装后，实际安装的是 `1.1.0`以上的版本，通常来讲小版本升级不会影响运行，但是这个插件貌似不太一样，所以您可以 先卸载这个插件`sudo npm uninstall --save-dev chunk-manifest-webpack-plugin`, 然后安装指定版本的 `sudo npm install --save-dev chunk-manifest-webpack-plugin@1.1.0` ，另外，上传代码时，有一段用于移动端测试的代码忘记删除，可能会增加响应时间一分钟左右，2017.8.25 更新的版本已经删除（包括软件版本的问题）
