### ISSUE TITLE
ie浏览器完全不兼容

### ISSUE THREAD

**Issue by answer33** [mjzhang1993/react-router4-template#2]
我加了options: {presets: ['es2015', 'react', 'stage-2']} 还有vendor里也加了babel-polyfill  还是不行  语法报错 不知道为什么

**Comment by mjzhang1993** [comment]
已经更新了新的版本，如果还是报错，可以检查一下 node 版本，我这里使用的是 v8.9.0 版本的 babel 的配置，我写在的 .babelrc 文件中了，这次没有使用babel-polyfill，但是当前的配置绝大部分的 es6+ 都可以使用，置于 IE 兼容问题，原本的模板是适用于移动端的，开发测试都是在 Chrome 下进行的， Firefox 也可以，IE 没有在开发环境测试
