### ISSUE TITLE
yarn install 报错

### ISSUE THREAD

**Issue by lwx405540** [mjzhang1993/react-router4-template#3]
Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

D:\code\github\react-router4-template>yarn install
yarn install v1.3.2
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "http://registry.npm.taobao.org/history/down
load/history-4.7.2.tgz: connect EACCES 114.55.80.225:80".
info If you think this is a bug, please open a bug report with the information p
rovided in "D:\\code\\github\\react-router4-template\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this
command.

D:\code\github\react-router4-template>

**Comment by mjzhang1993** [comment]
通过以上提供的信息实在看不出来问题所在，这里可以提供几个可以尝试的意见：1. 淘宝镜像：我这里的淘宝镜像地址是 ‘https://registry.npm.taobao.org/’ https 的，可以通过命令 `yarn config get registry` 命令查询是否一致；2. 如果还是有问题，可以尝试将根目录下的 node_modules 文件夹和 yarn.lock 文件删除，然后重新 `sudo yarn install`；3. node 版本不能太低，建议升级到 8.x.x
